title: BiEffect
email: bieffect@yahoo.com
author: A. Moghaddas
url: https://bieffect.github.io
github_username: BiEffect
telegram_username: BiEffect

lang: fa_IR
timezone: Asia/Tehran

comment_system: disqus
disqus_shortname: bieffect-github-io

google_analytics: UA-128630662-1
google_cse_id: 006217176783083543730:ip1ifikfuq8

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
