title: BiEffect
email: bieffect@yahoo.com
author: Ali Moghaddas
url: https://bieffect.github.io
github_username: BiEffect
twitter_username: BiEffect1

lang: fa_IR
timezone: Asia/Tehran

comment_system: disqus
disqus_shortname: bieffect-github-io

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
